### ISSUE TITLE
delete this downloaded tarfile?

### ISSUE THREAD

**Issue by hyphaltip** [jolespin/veba#1]
Do you want to also delete  `GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar.gz` when this step has uncompressed the bowtie indexes?
https://github.com/jolespin/veba/blob/0c9728cc42258a9956f2c531a9eafabfeacd6bb8/install/download_databases.sh#L114

Note that downloads for nr.gz could go faster with aspera too
eg
`ascp -i $ASPERAKEY -QT -l 500m anonftp@ftp.ncbi.nlm.nih.gov:/blast/db/FASTA/nr.gz .` 
https://github.com/jolespin/veba/blob/0c9728cc42258a9956f2c531a9eafabfeacd6bb8/install/download_databases.sh#L100

**Comment by jolespin** [comment]
>Do you want to also delete GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar.gz when this step has uncompressed the bowtie indexes?

Thanks for catching this.  I mean to remove the .tar.gz after it gets decompressed.  Fixing it now.  Also, I'm thinking about changing the default human reference to the T2T instead of the GRch38 no alt analysis.  Need to look into the caveats.

>Note that downloads for nr.gz could go faster with aspera too
I'll look into this.  A large part of the user base will not have an aspera key and I don't want to add a barrier to entry for them.  However, I could do a conditional that downloads via ascp if a user has an aspera key available.  I'll keep this in mind.

**Comment by jolespin** [comment]
Just wanted to update you that I've swapped out GRCh38 no alt analysis for CHM13v2.0 (the telomere-to-telomere build) in the following commit: https://github.com/jolespin/veba/commit/5ccb4e20564513707fcc3420b18237974455e196
