### ISSUE TITLE
[Typo] Installation Guide bash update_environment_variables.sh

### ISSUE THREAD

**Issue by erfanshekarriz** [jolespin/veba#16]
Hi Josh, 

I've noticed a small typo here. 

- In the installation guide you mention:
`bash update_environment_variables.sh
`

- In the update guide you mention 
`  bash veba/install/update_environment_variables.sh /path/to/veba_database
`

From the bash script, it seems like the database directory needs to be the first command argument so I thought it might be a typo. 

I also wanted to ask if you prefer me to report typos by other means like email to stop the issues on GitHub from getting overcrowded.

Let me know which is best, 

Erfan

**Comment by jolespin** [comment]
> I've noticed a small typo here.
> 
> In the installation guide you mention:
> bash update_environment_variables.sh
> 
> In the update guide you mention
> bash veba/install/update_environment_variables.sh /path/to/veba_database

The order of operations for installation is the following: 

1.  Create the environments: https://github.com/jolespin/veba/blob/f2095b62c60eca18d95856e917b54ef2abd5332c/install/install_veba.sh#L23
2. Copy the modules/scripts into the environments: https://github.com/jolespin/veba/blob/f2095b62c60eca18d95856e917b54ef2abd5332c/install/install_veba.sh#L26
3. Download/configure the databases: https://github.com/jolespin/veba/blob/main/install/download_databases.sh
4. Create activate/deactivate scripts in each environment and export/unset the necessary environment variables: https://github.com/jolespin/veba/blob/f2095b62c60eca18d95856e917b54ef2abd5332c/install/download_databases.sh#L142

Are you referring to the [PATCH documentation](https://github.com/jolespin/veba/blob/main/install/PATCHES.md)? 

If so, that's just to "patch" an existing installation.  It's what I use when I'm doing minor updates instead of reinstalling everything from scratch everytime which would be SUPER frustrating haha. 

The `update_environment_scripts.sh` basically just copies over scripts into the path for the different environments: https://github.com/jolespin/veba/blob/main/install/update_environment_scripts.sh

The `update_environment_variables.sh` is for when you create a new environment or change database locations and need to update the export/unset environment variables in the activate/deactivate scripts: https://github.com/jolespin/veba/blob/main/install/update_environment_variables.sh

>From the bash script, it seems like the database directory needs to be the first command argument so I thought it might be a typo

Definitely.  Let me know if the above doesn't make sense. 

>I also wanted to ask if you prefer me to report typos by other means like email to stop the issues on GitHub from getting overcrowded.

These issues have really helpful and they are really organized with titles and tags.  I think it's important for users/people to see the process in how the software is developed and tweaked.  Been looking into the idea of [decentralized science](https://www.nature.com/articles/s41587-022-01459-z) and very into the culture of transparency. Your insight has been extremely helpful btw!

**Comment by erfanshekarriz** [comment]
Hi Josh, 

Awesome and thanks for the explanations! Agree with your mention of software development process, but I know different people might have different preferences. 

Thanks for your help as always, 

Best, 

Erfan
