### ISSUE TITLE
Duplicate scaffold/contig identifiers are not allowed

### ISSUE THREAD

**Issue by MACampbell91** [jolespin/veba#25]
Hi Josh,

I am comparing the regular workflow to the co-assembly method on a small subset of my own samples. When running cluster.py of the co-assemblies, I am getting a duplicate scaffold/contig identifiers error, however it works perfectly fine with the regular workflow. 

For instance

1__global_clustering.e

"Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/VEBA-cluster_env/bin/scripts/global_clustering.py", line 466, in <module>
    main(sys.argv[1:])
  File "/home/ubuntu/miniconda3/envs/VEBA-cluster_env/bin/scripts/global_clustering.py", line 207, in main
    assert id_scaffold not in scaffold_to_mag, "Duplicate scaffold/contig identifiers are not allowed: {} from {}".format(id_scaffold, row["genome"])
AssertionError: Duplicate scaffold/contig identifiers are not allowed: coassembly__k141_330954 from veba_output/binning/prokaryotic/S12/output/genomes/S12__METABAT2__P.2__bin.7.fa"

Is there a way around this?

Cheers,

Matt

**Comment by jolespin** [comment]
Which version are you running? 

This was an issue that I thought would be extremely rare but apparently it happens when there are enough samples.  I ended up adding a prefix option in this commit: https://github.com/jolespin/veba/commit/d31b0d91f3c8122e8bf8ee45c9ef36cea04ca6e7
https://github.com/jolespin/veba/blob/main/DEVELOPMENT.md#change-log [2023.3.7]

It is available in v1.1.1 using the following argument: 
```
    parser_assembler.add_argument("-s", "--scaffold_prefix", type=str, default="NAME__", help="Assembler |  Special options:  Use NAME to use --name.  Use NONE to not include a prefix. [Default: 'NAME__']")

```

You can follow this guide to update your scripts to v1.1.1 it's really easy: 
https://github.com/jolespin/veba/blob/main/install/PATCHES.md#1-update-veba-environments-with-existing-or-most-recent-scripts

Note, I would definitely do the v1.1.1 release that you download instead of cloning the current GitHub repository.  I'm making a bunch of updates right now and need to test everything for v1.1.2 release.

**Comment by MACampbell91** [comment]
Hi Josh,

I did have v1.1.1 installed but I ran the update_environment_scripts.sh anyway. Unfortunately, it didn't work and the same error occurred. I also tried uninstalling and reinstalling v1.1.1 but same issue still appeared.  At what step is parser_assembler.add_argument("-s", "--scaffold_prefix", type=str, default="NAME__", help="Assembler |  Special options:  Use NAME to use --name.  Use NONE to not include a prefix. [Default: 'NAME__']") occurring?

Cheers

**Comment by jolespin** [comment]
Are you still having trouble with this?

**Comment by jolespin** [comment]
> Hi Josh,
> 
> I did have v1.1.1 installed but I ran the update_environment_scripts.sh anyway. Unfortunately, it didn't work and the same error occurred. I also tried uninstalling and reinstalling v1.1.1 but same issue still appeared. At what step is parser_assembler.add_argument("-s", "--scaffold_prefix", type=str, default="NAME__", help="Assembler | Special options: Use NAME to use --name. Use NONE to not include a prefix. [Default: 'NAME__']") occurring?
> 
> Cheers

It's added here at this stage: 
https://github.com/jolespin/veba/blob/main/src/assembly.py#L155

**Comment by MACampbell91** [comment]
Hi Josh,

Just to clarify.

Would the assembly look something like this "assembly.py -1 ${R1} -2 ${R2} -n ${ID} -o ${OUT_DIR} -p ${N_JOBS} --name NONE" to revolve the problem?

Cheers

**Comment by jolespin** [comment]
Are you still having this issue? 

I just pushed the v1.2.0 major update.

**Comment by jolespin** [comment]
Please provide some more info and reopen ticket if this is still occurring.  I'd be happy to help resolve this.
