### ISSUE TITLE
[Question] What does the homogenity value mean in the output taxonomy.tsv file of classify-eukaryotic

### ISSUE THREAD

**Issue by franlat** [jolespin/veba#29]
Hello, 

I recently was trying to run VEBA 1.2.0 on some of my already-built eukaryotic MAGs to assess their taxonomy with the veba_classify module. While the program worked smoothly, I don't know if I understand the output of the taxonomy.csv file given by the classify-eukaryotic.py script. What does the homogeneity value represent? Some of the taxonomy given is very specific (species level), but how accurate is it?

Thank you!

PD. Fantastic work with VEBA! Looks like a very promising tool for microeukaryotic metagenomics.

**Comment by jolespin** [comment]
This one must have slipped through the cracks.  For some reason I'm not getting e-mail notifications for new issues. 

Here's the relevant code: 
https://github.com/jolespin/veba/blob/a1844bd4605c2828ca6d5ff11488efba9e778f9e/src/scripts/consensus_genome_classification.py#L116

```
    # Get container for scores [SLC -> Taxonomy -> Score]
    #
    # For example the following MAG: 
    # CLASSIFICATION=d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Mycobacteriales;f__Mycobacteriaceae;g__Corynebacterium;s__Corynebacterium aurimucosum_E
    # MSA_PERCENT=80.0
    #
    # Would be stored and appended for it's corresponding SLC:
    # d__Bacteria += 80.0
    # d__Bacteria;p__Actinobacteriota += 80.0
    # d__Bacteria;p__Actinobacteriota;c__Actinomycetia += 80.0
    # d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Mycobacteriales += 80.0
    # d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Mycobacteriales;f__Mycobacteriaceae += 80.0
    # d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Mycobacteriales;f__Mycobacteriaceae;g__Corynebacterium += 80.0
    # d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Mycobacteriales;f__Mycobacteriaceae;g__Corynebacterium;s__Corynebacterium aurimucosum_E += 80.0

    slc_taxa_scores = defaultdict(lambda: defaultdict(float))
    
    # Iterate through MAG, classification, and score
    df = pd.concat([genome_to_slc.to_frame("id"), classification.to_frame("classification"), classification_weights.to_frame("weight")], axis=1)
    slc_to_mags = defaultdict(list)
    for id_mag, (id_slc, classification, w) in df.iterrows():
        slc_to_mags[id_slc].append(id_mag)
        # Split the taxonomy classification by levels
        levels = classification.split(delimiter)
        # Remove the empty taxonomy levels (e.g., g__Corynebacterium;s__ --> g__Corynebacterium)
        levels = list(filter(lambda x:x not in rank_prefixes, levels))
        number_of_query_levels = len(levels)
        # Iterate through each level, scale score by the leniency weights, and add to running sum
        for i in range(1, number_of_query_levels + 1):
            weighted_score = float(w) * scaling_factors[i-1]
            slc_taxa_scores[id_slc][tuple(levels[:i])] += weighted_score

...


    # Homogeneity
    slc_taxa_homogeneity = defaultdict(lambda: defaultdict(float))
    for id_slc, (classifications, weights) in df_consensus_classification[["classifications", "weights"]].iterrows():
        for (c, w) in zip(classifications, weights):
            slc_taxa_homogeneity[id_slc][c] += w
    df_consensus_classification["homogeneity"] = pd.DataFrame(slc_taxa_homogeneity).T.apply(lambda x: np.nanmax(x)/np.nansum(x), axis=1)
```

It's based on a weighted score and the homogeneity is the maximum score divided by the total score.

**Comment by franlat** [comment]
Ok, I think I get it. Just two more questions:

1. How are these weights calculated? Is it from a database?

2. What would you say is the threshold of homogeneity to trust the given taxonomy? I'll give you an example: I did a test with four genomes that I know what they are: species A, B, C and E. All four of them are from the same phylogenetic group. In the VEBA database, three of them have references in it (A, C and E). So, species A and E were assigned the correct taxonomy and homogeneity > 70% (super cool! because these are uncultured organisms that are usually under-represented in DBs). Although species C is in the DB, many hits were with species A reference, so the final taxonomy was at the family level (instead of genus) and the homogeneity was lower (which is not bad either, this is what I would expect). However, since species B is not in the DB, it was assigned the closest match in the tree: species A. But the homogeneity was better than in the last case. Therefore, in a context where I don't know what the real taxonomy is, how should I use this homogeneity value to assess the taxonomy?

**Comment by jolespin** [comment]
>How are these weights calculated? Is it from a database?
For the gene calls, I use `MetaEuk` which uses `MMSEQS2` to align and calculate bitscores in the backend.  The scores that go into the consensus annotation script is a running some of the bitscores to the source genome. 
https://github.com/jolespin/veba/blob/a1844bd4605c2828ca6d5ff11488efba9e778f9e/src/scripts/compile_eukaryotic_classifications.py

>What would you say is the threshold of homogeneity to trust the given taxonomy? 

I'll have to test this out and will keep this in mind.  

I'm currently building a much more robust and clustered version of the database now that the restrictions of JGI data are more accessible.  But to be honest, these alignment and guilt-by-association methods are only as good as the databases and will unfortunately have to make due until someone takes the time to build something more robust like GTDB-Tk for eukaryotes.  

> I'll give you an example: I did a test with four genomes that I know what they are: species A, B, C and E. 


Would you mind sharing these genomes and their known taxonomy? If that's not possible, can you provide the taxonomy of the organisms so I can test them to help and tune while keeping these in mind? 

>Although species C is in the DB, many hits were with species A reference, so the final taxonomy was at the family level (instead of genus) and the homogeneity was lower (which is not bad either, this is what I would expect). 

One thing you can do is adjust the leniency parameter which weights the different taxonomic levels differently. 

Another thing you can try is just using the genomes for the classification and not the binning directory.  The difference here would be that genes would be called only using the eukaryota_odb10 hits which might give better performance.

>Therefore, in a context where I don't know what the real taxonomy is, how should I use this homogeneity value to assess the taxonomy?

The truth is that I don't have an answer to this question at the moment but it comes at the perfect time because (as mentioned earlier) I'm working on an updated database and will also update the classification scripts as well!  I can include it in the benchmarking.

**Comment by franlat** [comment]
> Would you mind sharing these genomes and their known taxonomy? If that's not possible, can you provide the taxonomy of the organisms so I can test them to help and tune while keeping these in mind?

Of course, these genomes were published two years ago. Here is the link to the genomes and gene prediction: https://doi.org/10.6084/m9.figshare.13072322

I'm putting here the first three columns from the ` taxonomy.tv given by VEBA:

> id      consensus_classification        homogeneity
MAST4A  c__MAST;o__MAST-4;f__MAST-4;g__MAST-4A;s__MAST-4A [nan] 0.7045810862678004
MAST4C  c__MAST;o__MAST-4;f__MAST-4;g__;s__     0.42722392066214304
MAST4B  c__MAST;o__MAST-4;f__MAST-4;g__MAST-4A;s__      0.5770911271668047
MAST4E  c__MAST;o__MAST-4;f__MAST-4;g__MAST-4E;s__MAST-4E [nan] 0.833090853555611

> Another thing you can try is just using the genomes for the classification and not the binning directory. The difference here would be that genes would be called only using the eukaryota_odb10 hits which might give better performance.

I did that for these four genomes since these are not MAGs. I assembled and cleaned these genomes from Single-Cell Genomics data. 

Let me know if I can help in any way! Microeukaryotes need some love!

**Comment by jolespin** [comment]
Oh yea, I was actually just looking at these (I believe from MMETSP?).  These are tricky organisms because each of their taxonomic levels are not well characterized.

That's another thing about eukaryotic taxonomic classifications.  It's messy and full of unstructured clades.

Excellent test case! Thanks again for sharing your insight.

**Comment by franlat** [comment]
I have some Single-Cell data from organisms that I know what they are. So I'll keep testing VEBA there and I'll let you know what are my findings!

**Comment by jolespin** [comment]
Sounds great.  Closing this for now but feel free to continue commenting and reopen if you feel it wasn't resolved. Cheers.

Again, the new database I'm building right now should be much more comprehensive and accurate.
